// <auto-generated />
using System;
using LCFilaApplication.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LCFilaApplication.Migrations
{
    [DbContext(typeof(FilaDbContext))]
    [Migration("20211121201655_renameaspnetidentitytables")]
    partial class renameaspnetidentitytables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Identity")
                .HasAnnotation("ProductVersion", "3.1.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LCFilaApplication.Models.EmpresaConfiguracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorPrincipalEmpresa")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CorSegundariaEmpresa")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FooterEmpresa")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LinkLogodaEmpresa")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NomeDaEmpresa")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("EmpresaConfiguracaos");
                });

            modelBuilder.Entity("LCFilaApplication.Models.EmpresaLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<Guid?>("EmpresaConfiguracaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdAdminEmpresa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaConfiguracaoId");

                    b.ToTable("EmpresaLogins");
                });

            modelBuilder.Entity("LCFilaApplication.Models.Fila", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EmpresaLoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TempoMedio")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaLoginId");

                    b.ToTable("Filas");
                });

            modelBuilder.Entity("LCFilaApplication.Models.FilaMercadoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FiladeMercadoriasId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FiladeMercadoriasId");

                    b.ToTable("FilaMercadorias");
                });

            modelBuilder.Entity("LCFilaApplication.Models.FilaPessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FiladePessoasId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FiladePessoasId");

                    b.ToTable("FilaPessoas");
                });

            modelBuilder.Entity("LCFilaApplication.Models.FilaVeiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FiladeVeiculosId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FiladeVeiculosId");

                    b.ToTable("FilaVeiculos");
                });

            modelBuilder.Entity("LCFilaApplication.Models.Mercadoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Dimensoes")
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("FilaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FilaMercadoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Identificacao")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Peso")
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("FilaId");

                    b.HasIndex("FilaMercadoriaId");

                    b.ToTable("Mercadorias");
                });

            modelBuilder.Entity("LCFilaApplication.Models.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Celular")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Documento")
                        .HasColumnType("varchar(14)");

                    b.Property<Guid>("FilaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FilaPessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Posicao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FilaId");

                    b.HasIndex("FilaPessoaId");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("LCFilaApplication.Models.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Fabricante")
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("FilaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FilaVeiculoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Modelo")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TipoVeiculo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FilaId");

                    b.HasIndex("FilaVeiculoId");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("LCFilaApplication.Models.AppUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<Guid?>("empresaLoginId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("empresaLoginId");

                    b.HasDiscriminator().HasValue("AppUser");
                });

            modelBuilder.Entity("LCFilaApplication.Models.EmpresaLogin", b =>
                {
                    b.HasOne("LCFilaApplication.Models.EmpresaConfiguracao", "EmpresaConfiguracao")
                        .WithMany()
                        .HasForeignKey("EmpresaConfiguracaoId");
                });

            modelBuilder.Entity("LCFilaApplication.Models.Fila", b =>
                {
                    b.HasOne("LCFilaApplication.Models.EmpresaLogin", null)
                        .WithMany("EmpresaFilas")
                        .HasForeignKey("EmpresaLoginId");
                });

            modelBuilder.Entity("LCFilaApplication.Models.FilaMercadoria", b =>
                {
                    b.HasOne("LCFilaApplication.Models.Fila", "FiladeMercadorias")
                        .WithMany()
                        .HasForeignKey("FiladeMercadoriasId");
                });

            modelBuilder.Entity("LCFilaApplication.Models.FilaPessoa", b =>
                {
                    b.HasOne("LCFilaApplication.Models.Fila", "FiladePessoas")
                        .WithMany()
                        .HasForeignKey("FiladePessoasId");
                });

            modelBuilder.Entity("LCFilaApplication.Models.FilaVeiculo", b =>
                {
                    b.HasOne("LCFilaApplication.Models.Fila", "FiladeVeiculos")
                        .WithMany()
                        .HasForeignKey("FiladeVeiculosId");
                });

            modelBuilder.Entity("LCFilaApplication.Models.Mercadoria", b =>
                {
                    b.HasOne("LCFilaApplication.Models.Fila", "Fila")
                        .WithMany()
                        .HasForeignKey("FilaId")
                        .IsRequired();

                    b.HasOne("LCFilaApplication.Models.FilaMercadoria", null)
                        .WithMany("Mercadorias")
                        .HasForeignKey("FilaMercadoriaId");
                });

            modelBuilder.Entity("LCFilaApplication.Models.Pessoa", b =>
                {
                    b.HasOne("LCFilaApplication.Models.Fila", "Fila")
                        .WithMany()
                        .HasForeignKey("FilaId")
                        .IsRequired();

                    b.HasOne("LCFilaApplication.Models.FilaPessoa", null)
                        .WithMany("Pessoas")
                        .HasForeignKey("FilaPessoaId");
                });

            modelBuilder.Entity("LCFilaApplication.Models.Veiculo", b =>
                {
                    b.HasOne("LCFilaApplication.Models.Fila", "Fila")
                        .WithMany()
                        .HasForeignKey("FilaId")
                        .IsRequired();

                    b.HasOne("LCFilaApplication.Models.FilaVeiculo", null)
                        .WithMany("Veiculos")
                        .HasForeignKey("FilaVeiculoId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LCFilaApplication.Models.AppUser", b =>
                {
                    b.HasOne("LCFilaApplication.Models.EmpresaLogin", "empresaLogin")
                        .WithMany("UsersEmpresa")
                        .HasForeignKey("empresaLoginId");
                });
#pragma warning restore 612, 618
        }
    }
}
