name: ♻️ Refactor
description: Something that needs improving while not changing functionality
title: "♻️ [REFACTOR] - <title>"
labels: ["refactor", "triage"]
projects: ["projects/2"]
assignees:
  - luigicfilho
body:
  - type: textarea
    id: pain
    attributes:
      label: "Pain"
      description: Explain the pain you are experiencing.
      placeholder: Short and explicit description of the pain...
  - type: textarea
    id: code-to-be-improved
    attributes:
      label: "What code could be improved?"
      description: Add a link to the area/file that needs refactoring.
      placeholder: Identify the code that needs refactoring...
  - type: textarea
    id: acceptance
    attributes:
      label: "Acceptance Criteria"
      description: Define the criteria that will be satisfied the pain ? .
      placeholder: Acceptance Criteria helps to answer the question "How will I know when I'm done with this story?". It defines the requirements that must be met for the story to be completed...
  - type: textarea
    id: more
    attributes:
      label: "More Information"
      description: Any additional information.
      placeholder: Add any other context here...
